### ISSUE TITLE
Incorrect Unicode Version in Documentation

### ISSUE THREAD

**Issue by KeqingMoe** [lighttransport/unicode-xid-cpp#1]
I've noticed an error in our documentation regarding the specified Unicode version. The version is currently listed as "5.1.0," but the correct version should be "15.1.0."

**Comment by syoyo** [comment]
Good find! Yes, it should be `15.1.0`

We also need to modify comments in the code, e.g. https://github.com/lighttransport/unicode-xid-cpp/blob/3e7586d8fc021dea997ed71d86a08abbc6d2849e/unicode-xid.hh#L6

PR is much appreciated!
